### ISSUE TITLE
Import XLSX file, getting error as Could not load file or assembly 'NPOI.OpenXmlFormats, Version=2.2.0.0

### ISSUE THREAD

**Issue by stplajay** [tonyqus/toxy#12]
Hi,
I am able to import .XLS file in my C# project but when i try to import .XLSX file (into DataTable) i am getting following reference issues.
1. Could not load file or assembly 'ICSharpCode.SharpZipLib - (I had found and added in my project)
2. Could not load file or assembly 'NPOI.OpenXmlFormats, Version=2.2.0.0 - (I could not found the .dll file, please provide me this file)

Please also let me know if the above can resolve my issue.
![exception](https://cloud.githubusercontent.com/assets/13213492/21978604/45fdbe56-dc01-11e6-9990-773611aee447.png)

**Comment by tonyqus** [comment]
Did you try latest Toxy nuget version? 

Sent from YoMail

< stplajay> 2017-01-16 18:04:36 wrote: 
Hi,
I am able to import .XLS file in my C# project but when i try to import .XLSX file (into DataTable) i am getting following reference issues.

Could

**Comment by stplajay** [comment]
Hi,
Thanks for your quick response. I explored more and found that i was not using correct version of ICSharpCode.SharpZipLib.dll and NPOI.OpenXmlFormats and both are required to import .XLSX files.

I included the correct version and able to import now. 
Thanks for your attention for this.
